=== abararsheikh/XML-LABS/Week 2 DTD/In class/dtd/External/song.dtd
<!ELEMENT SONG (TITLE,COMPOSER+,PRODUCER,PUBLISHER,LENGTH?,YEAR,address,ARTIST*,ab) >
        <!ELEMENT TITLE (#PCDATA) >
        <!ELEMENT COMPOSER (#PCDATA) >
        <!ELEMENT PRODUCER (#PCDATA) >
        <!ELEMENT PUBLISHER (#PCDATA) >
        <!ELEMENT LENGTH (#PCDATA) >
        <!ELEMENT YEAR (#PCDATA) >
        <!ELEMENT address (street,country, ( zipcode | postalcode) ) >
        <!ELEMENT street (#PCDATA) >
        <!ELEMENT country (#PCDATA) >
        <!ELEMENT zipcode (#PCDATA) >
        <!ELEMENT postalcode (#PCDATA) >
        <!ELEMENT ARTIST (#PCDATA | city )* >
        <!ELEMENT city (#PCDATA) >
        <!ELEMENT ab EMPTY >
        <!ATTLIST
                TITLE songid ( aa | bb | cc) #REQUIRED


        >

=== abararsheikh/XML-LABS/Week 2 DTD/In class/dtd/External/songext.xml
<?xml version="1.0"?>
<!DOCTYPE  SONG SYSTEM 'song.dtd' >

<SONG>
    <TITLE songid="aa">Hot Cop </TITLE>
    <COMPOSER>Jacques Morali</COMPOSER>
    <COMPOSER>Henri Belolo</COMPOSER>
    <COMPOSER>Victor Willis</COMPOSER>
    <PRODUCER>Jacques Morali</PRODUCER>
    <PUBLISHER>PolyGram Records</PUBLISHER>
    <LENGTH>6:20</LENGTH>
    <YEAR>1978</YEAR>
    <address>
        <street>111</street>
        <country>aa</country>
        <postalcode>1234</postalcode>
    </address>
    <ARTIST>Village People
        <city>Toronto</city>
    </ARTIST>
    <ab></ab>
</SONG>
