=== abararsheikh/XML-LABS/Midterm-Abarar Sheikh/internalmemo.dtd
<!ELEMENT internalmemo (header,body)>

        <!ELEMENT header (date,sender,recipients,blind-recipients?,subject)>

        <!ELEMENT body (para+,sig)>

        <!ELEMENT date (#PCDATA)>

        <!ELEMENT sender (#PCDATA)>

        <!ELEMENT recipients (#PCDATA)>

        <!ELEMENT blind-recipients (#PCDATA)>

        <!ELEMENT subject (#PCDATA)>

        <!ELEMENT sig (#PCDATA)>

        <!ELEMENT para (#PCDATA|b|i)*>

        <!ELEMENT b (#PCDATA)>

        <!ELEMENT i (#PCDATA)>

        <!ATTLIST internalmemo

                priority (low|medium|high) #REQUIRED

                initials CDATA #REQUIRED

                expiredate CDATA #REQUIRED

                origin (marketing|accounting|finance|hq|sales|ops) #REQUIRED>

=== abararsheikh/XML-LABS/Midterm-Abarar Sheikh/internalmemo.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE  internalmemo SYSTEM 'internalmemo.dtd' >
<internalmemo priority ="low" initials ="signature" expiredate ="next week" origin ="marketing" >
    <header>
        <date> 03/01/2016 </date>
        <sender> Abrar </sender>
        <recipients> Navaz  </recipients>
        <blind-recipients> Amrin </blind-recipients>
        <subject>Reminder  </subject>
    </header>
        <body>
            <para> </para>
            <para> </para>
            <para>Hello
               <b>How</b>
                <i>are you</i>
            </para>

            <sig> A.s.sheikh </sig>

        </body>

</internalmemo>
